export enum RoomsActions {
    SET_ROOMS = "SET_ROOMS",
    ADD_ROOM = "ADD_ROOM",
    REMOVE_ROOM = "REMOVE_ROOM",
    ADD_SOCKET_TO_ROOM = "ADD_SOCKET_TO_ROOM",
    REMOVE_SOCKET_FROM_ROOM = "REMOVE_SOCKET_FROM_ROOM",
    UPDATE_ROOM_VIDEO = "UPDATE_ROOM_VIDEO",
}
