export const colors = {
    brand: {
        default: "#a33346",
        light: "#da455e",
        dark: "#7a2634",
        900: "var(--chakra-colors-brand-default)",
        800: "var(--chakra-colors-brand-default)",
        700: "var(--chakra-colors-brand-default)",
        600: "var(--chakra-colors-brand-default)",
        500: "var(--chakra-colors-brand-default)",
        400: "var(--chakra-colors-brand-default)",
        300: "var(--chakra-colors-brand-default)",
        200: "var(--chakra-colors-brand-default)",
        100: "var(--chakra-colors-brand-default)",
        50: "var(--chakra-colors-brand-default)",
    },
    secondary: {
        default: "#2064f5",
        light: "#19abff",
        dark: "#242f46",
        900: "var(--chakra-colors-secondary-default)",
        800: "var(--chakra-colors-secondary-default)",
        700: "var(--chakra-colors-secondary-default)",
        600: "var(--chakra-colors-secondary-default)",
        500: "var(--chakra-colors-secondary-default)",
        400: "var(--chakra-colors-secondary-default)",
        300: "var(--chakra-colors-secondary-default)",
        200: "var(--chakra-colors-secondary-default)",
        100: "var(--chakra-colors-secondary-default)",
        50: "var(--chakra-colors-secondary-default)",
    },
    gray: {
        900: "#141414",
        800: "#191919",
        700: "#1e1e1e",
        600: "#232323",
        500: "#282828",
        400: "#2d2d2d",
        300: "#323232",
        200: "#373737",
        100: "#3c3c3c",
    },
    danger: "var(--chakra-colors-red-600)",
    success: "var(--chakra-colors-green-600)",
    textMuted: "var(--chakra-colors-whiteAlpha-500)",
};
